from __future__ import annotations

from .domain import build_evidence_template, classify_product, iso_days_from_now


SEED_SETTINGS = {
    "merchant_name": "Northstar Kids Co.",
    "default_owner": "Avery Chen",
    "jurisdictions": "United States, Canada",
    "catalog_mode": "demo",
    "cpsc_feed_mode": "live-ready",
}


PRODUCTS = [
    {
        "id": "prod-meadownest-high-chair",
        "shopify_product_id": "gid://shopify/Product/1001",
        "title": "MeadowNest Convertible High Chair",
        "handle": "meadownest-convertible-high-chair",
        "vendor": "Northstar Kids",
        "product_type": "High Chair",
        "status": "active",
        "jurisdiction_scope": "US, CA",
        "supplier_name": "Hefei YoungSprout Home Co.",
        "country_of_origin": "CN",
        "age_grade": "6m+",
        "tags": ["durable infant", "feeding", "high chair", "infant"],
        "variants": [
            {
                "id": "var-meadownest-sage",
                "shopify_variant_id": "gid://shopify/ProductVariant/2001",
                "sku": "MN-HC-SAGE",
                "title": "Sage",
                "barcode": "850100000001",
                "price": 189.0,
                "inventory_quantity": 42,
                "status": "active",
            },
            {
                "id": "var-meadownest-oat",
                "shopify_variant_id": "gid://shopify/ProductVariant/2002",
                "sku": "MN-HC-OAT",
                "title": "Oat",
                "barcode": "850100000002",
                "price": 189.0,
                "inventory_quantity": 31,
                "status": "active",
            },
        ],
        "documents": [
            {"id": "doc-mn-cpc", "title": "CPC - MeadowNest High Chair", "doc_type": "CPC", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-180), "valid_until": iso_days_from_now(185), "verified_at": iso_days_from_now(-21), "source_url": "", "notes": "References ASTM F404 and lead content limits."},
            {"id": "doc-mn-lab", "title": "Intertek lab report", "doc_type": "Lab Report", "issuer": "Intertek", "status": "verified", "issued_at": iso_days_from_now(-140), "valid_until": iso_days_from_now(90), "verified_at": iso_days_from_now(-35), "source_url": "", "notes": "Mechanical, stability, and coating scope."},
            {"id": "doc-mn-track", "title": "Tracking label artwork", "doc_type": "Tracking Label", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-60), "valid_until": iso_days_from_now(240), "verified_at": iso_days_from_now(-20), "source_url": "", "notes": "Lot/date code embedded on underside label."},
            {"id": "doc-mn-manual", "title": "Instruction manual v3", "doc_type": "Manual", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-45), "valid_until": iso_days_from_now(320), "verified_at": iso_days_from_now(-18), "source_url": "", "notes": "Consumer setup and restraint instructions."},
            {"id": "doc-mn-supplier", "title": "Factory conformity packet", "doc_type": "Supplier Packet", "issuer": "YoungSprout Home", "status": "supplier_sent", "issued_at": iso_days_from_now(-430), "valid_until": iso_days_from_now(-3), "verified_at": iso_days_from_now(-410), "source_url": "", "notes": "Needs refreshed plating attestation."},
        ],
        "missing_requirements": ["registration_card"],
    },
    {
        "id": "prod-littleharbor-carrier",
        "shopify_product_id": "gid://shopify/Product/1002",
        "title": "LittleHarbor Infant Carrier",
        "handle": "littleharbor-infant-carrier",
        "vendor": "Northstar Kids",
        "product_type": "Carrier",
        "status": "active",
        "jurisdiction_scope": "US, CA",
        "supplier_name": "Quanzhou Harbor Motion Tech",
        "country_of_origin": "VN",
        "age_grade": "0-12m",
        "tags": ["durable infant", "carrier", "travel"],
        "variants": [
            {
                "id": "var-lh-ash",
                "shopify_variant_id": "gid://shopify/ProductVariant/2003",
                "sku": "LH-CR-ASH",
                "title": "Ash",
                "barcode": "850100000003",
                "price": 139.0,
                "inventory_quantity": 25,
                "status": "active",
            }
        ],
        "documents": [
            {"id": "doc-lh-cpc", "title": "CPC - LittleHarbor Carrier", "doc_type": "CPC", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-120), "valid_until": iso_days_from_now(240), "verified_at": iso_days_from_now(-26), "source_url": "", "notes": "References 16 CFR 1226 and flammability scope."},
            {"id": "doc-lh-lab", "title": "SGS carrier test report", "doc_type": "Lab Report", "issuer": "SGS", "status": "verified", "issued_at": iso_days_from_now(-110), "valid_until": iso_days_from_now(210), "verified_at": iso_days_from_now(-26), "source_url": "", "notes": "Includes buckle strength testing."},
            {"id": "doc-lh-track", "title": "Carrier traceability label", "doc_type": "Tracking Label", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-50), "valid_until": iso_days_from_now(260), "verified_at": iso_days_from_now(-12), "source_url": "", "notes": "Batch code on waist belt interior."},
            {"id": "doc-lh-reg", "title": "Consumer registration card", "doc_type": "Registration Proof", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-70), "valid_until": iso_days_from_now(280), "verified_at": iso_days_from_now(-17), "source_url": "", "notes": "QR and postcard flows captured."},
            {"id": "doc-lh-manual", "title": "Carrier instructions v4", "doc_type": "Manual", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-55), "valid_until": iso_days_from_now(330), "verified_at": iso_days_from_now(-17), "source_url": "", "notes": "Includes infant positioning warnings."},
            {"id": "doc-lh-supplier", "title": "Carrier supplier packet", "doc_type": "Supplier Packet", "issuer": "Harbor Motion", "status": "verified", "issued_at": iso_days_from_now(-90), "valid_until": iso_days_from_now(120), "verified_at": iso_days_from_now(-28), "source_url": "", "notes": "Current BOM and plastic resin declarations."},
        ],
        "missing_requirements": [],
    },
    {
        "id": "prod-cloudcradle-bassinet",
        "shopify_product_id": "gid://shopify/Product/1003",
        "title": "CloudCradle Bedside Bassinet",
        "handle": "cloudcradle-bedside-bassinet",
        "vendor": "Northstar Kids",
        "product_type": "Bassinet",
        "status": "active",
        "jurisdiction_scope": "US, CA",
        "supplier_name": "Hangzhou SoftNest Nursery",
        "country_of_origin": "CN",
        "age_grade": "0-5m",
        "tags": ["durable infant", "bassinet", "sleep"],
        "variants": [
            {
                "id": "var-cc-dune",
                "shopify_variant_id": "gid://shopify/ProductVariant/2004",
                "sku": "CC-BS-DUNE",
                "title": "Dune",
                "barcode": "850100000004",
                "price": 229.0,
                "inventory_quantity": 14,
                "status": "active",
            }
        ],
        "documents": [
            {"id": "doc-cc-cpc", "title": "CPC - CloudCradle Bassinet", "doc_type": "CPC", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-210), "valid_until": iso_days_from_now(120), "verified_at": iso_days_from_now(-35), "source_url": "", "notes": "Linked to bedside bassinet configuration."},
            {"id": "doc-cc-lab", "title": "Bassinet lab report", "doc_type": "Lab Report", "issuer": "Bureau Veritas", "status": "verified", "issued_at": iso_days_from_now(-450), "valid_until": iso_days_from_now(-10), "verified_at": iso_days_from_now(-420), "source_url": "", "notes": "Refresh required before next retail review."},
            {"id": "doc-cc-track", "title": "Bassinet tracking label proof", "doc_type": "Tracking Label", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-88), "valid_until": iso_days_from_now(220), "verified_at": iso_days_from_now(-22), "source_url": "", "notes": "Date code on mattress support bracket."},
            {"id": "doc-cc-reg", "title": "Bassinet registration card", "doc_type": "Registration Proof", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-72), "valid_until": iso_days_from_now(240), "verified_at": iso_days_from_now(-19), "source_url": "", "notes": "Registration card and QR archive."},
            {"id": "doc-cc-manual", "title": "Bassinet manual v2", "doc_type": "Manual", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-65), "valid_until": iso_days_from_now(300), "verified_at": iso_days_from_now(-19), "source_url": "", "notes": "Safe sleep instruction pack."},
        ],
        "missing_requirements": ["supplier_packet"],
    },
    {
        "id": "prod-brightloop-sorter",
        "shopify_product_id": "gid://shopify/Product/1004",
        "title": "BrightLoop Shape Sorter Toy",
        "handle": "brightloop-shape-sorter-toy",
        "vendor": "Northstar Kids",
        "product_type": "Toy",
        "status": "active",
        "jurisdiction_scope": "US, CA",
        "supplier_name": "Yiwu Little Spark Toys",
        "country_of_origin": "CN",
        "age_grade": "12m+",
        "tags": ["toy", "sorting", "wooden"],
        "variants": [
            {
                "id": "var-bl-primary",
                "shopify_variant_id": "gid://shopify/ProductVariant/2005",
                "sku": "BL-SS-PRIMARY",
                "title": "Primary",
                "barcode": "850100000005",
                "price": 39.0,
                "inventory_quantity": 64,
                "status": "active",
            }
        ],
        "documents": [
            {"id": "doc-bl-cpc", "title": "CPC - BrightLoop Sorter", "doc_type": "CPC", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-110), "valid_until": iso_days_from_now(200), "verified_at": iso_days_from_now(-17), "source_url": "", "notes": "Toy standard scope recorded."},
            {"id": "doc-bl-lab", "title": "Toy paint and mechanical report", "doc_type": "Lab Report", "issuer": "Intertek", "status": "verified", "issued_at": iso_days_from_now(-100), "valid_until": iso_days_from_now(200), "verified_at": iso_days_from_now(-17), "source_url": "", "notes": "Includes lead coating results."},
            {"id": "doc-bl-age", "title": "Age grading memo", "doc_type": "Age Grade", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-96), "valid_until": iso_days_from_now(220), "verified_at": iso_days_from_now(-16), "source_url": "", "notes": "12m+ rationale approved by product lead."},
            {"id": "doc-bl-supplier", "title": "Toy supplier packet", "doc_type": "Supplier Packet", "issuer": "Little Spark Toys", "status": "verified", "issued_at": iso_days_from_now(-83), "valid_until": iso_days_from_now(120), "verified_at": iso_days_from_now(-15), "source_url": "", "notes": "Current material declarations."},
        ],
        "missing_requirements": ["tracking_label"],
    },
    {
        "id": "prod-pebblepath-bath-seat",
        "shopify_product_id": "gid://shopify/Product/1005",
        "title": "PebblePath Baby Bath Seat",
        "handle": "pebblepath-baby-bath-seat",
        "vendor": "Northstar Kids",
        "product_type": "Bath Seat",
        "status": "active",
        "jurisdiction_scope": "US, CA",
        "supplier_name": "Ningbo WaterNest Products",
        "country_of_origin": "CN",
        "age_grade": "5m+",
        "tags": ["durable infant", "bath seat", "bath"],
        "variants": [
            {
                "id": "var-pp-mist",
                "shopify_variant_id": "gid://shopify/ProductVariant/2006",
                "sku": "PP-BS-MIST",
                "title": "Mist",
                "barcode": "850100000006",
                "price": 52.0,
                "inventory_quantity": 37,
                "status": "active",
            }
        ],
        "documents": [
            {"id": "doc-pp-cpc", "title": "CPC - PebblePath Bath Seat", "doc_type": "CPC", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-130), "valid_until": iso_days_from_now(200), "verified_at": iso_days_from_now(-18), "source_url": "", "notes": "Bath seat model covered."},
            {"id": "doc-pp-lab", "title": "Bath seat test report", "doc_type": "Lab Report", "issuer": "QIMA", "status": "verified", "issued_at": iso_days_from_now(-105), "valid_until": iso_days_from_now(165), "verified_at": iso_days_from_now(-20), "source_url": "", "notes": "Suction and stability scope."},
            {"id": "doc-pp-track", "title": "Bath seat traceability label", "doc_type": "Tracking Label", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-80), "valid_until": iso_days_from_now(245), "verified_at": iso_days_from_now(-14), "source_url": "", "notes": "Lot code molded into base."},
            {"id": "doc-pp-reg", "title": "Bath seat registration proof", "doc_type": "Registration Proof", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-78), "valid_until": iso_days_from_now(235), "verified_at": iso_days_from_now(-14), "source_url": "", "notes": "Registration flow captured."},
            {"id": "doc-pp-supplier", "title": "Bath seat supplier packet", "doc_type": "Supplier Packet", "issuer": "WaterNest", "status": "verified", "issued_at": iso_days_from_now(-82), "valid_until": iso_days_from_now(150), "verified_at": iso_days_from_now(-22), "source_url": "", "notes": "Current resin declarations."},
        ],
        "missing_requirements": ["instruction_manual"],
    },
    {
        "id": "prod-starstep-walker",
        "shopify_product_id": "gid://shopify/Product/1006",
        "title": "StarStep Activity Walker",
        "handle": "starstep-activity-walker",
        "vendor": "Northstar Kids",
        "product_type": "Walker",
        "status": "active",
        "jurisdiction_scope": "US, CA",
        "supplier_name": "Foshan Orbit Play Systems",
        "country_of_origin": "CN",
        "age_grade": "6m+",
        "tags": ["durable infant", "walker", "activity"],
        "variants": [
            {
                "id": "var-ss-sun",
                "shopify_variant_id": "gid://shopify/ProductVariant/2007",
                "sku": "SS-WK-SUN",
                "title": "Sun",
                "barcode": "850100000007",
                "price": 149.0,
                "inventory_quantity": 11,
                "status": "active",
            }
        ],
        "documents": [
            {"id": "doc-ss-cpc", "title": "CPC - StarStep Walker", "doc_type": "CPC", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-120), "valid_until": iso_days_from_now(200), "verified_at": iso_days_from_now(-19), "source_url": "", "notes": "Walker configuration covered."},
            {"id": "doc-ss-lab", "title": "Walker lab report", "doc_type": "Lab Report", "issuer": "Bureau Veritas", "status": "pending_review", "issued_at": iso_days_from_now(-20), "valid_until": iso_days_from_now(340), "verified_at": iso_days_from_now(-20), "source_url": "", "notes": "Awaiting internal sign-off after seat pad material change."},
            {"id": "doc-ss-track", "title": "Walker tracking label proof", "doc_type": "Tracking Label", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-72), "valid_until": iso_days_from_now(260), "verified_at": iso_days_from_now(-18), "source_url": "", "notes": "Date code on underside frame."},
            {"id": "doc-ss-reg", "title": "Walker registration proof", "doc_type": "Registration Proof", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-72), "valid_until": iso_days_from_now(260), "verified_at": iso_days_from_now(-18), "source_url": "", "notes": "Digital registration archive."},
            {"id": "doc-ss-manual", "title": "Walker instructions", "doc_type": "Manual", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-61), "valid_until": iso_days_from_now(310), "verified_at": iso_days_from_now(-13), "source_url": "", "notes": "Brake and stair warning present."},
            {"id": "doc-ss-supplier", "title": "Walker supplier packet", "doc_type": "Supplier Packet", "issuer": "Orbit Play", "status": "verified", "issued_at": iso_days_from_now(-88), "valid_until": iso_days_from_now(144), "verified_at": iso_days_from_now(-21), "source_url": "", "notes": "Current plastic declarations."},
        ],
        "missing_requirements": [],
    },
    {
        "id": "prod-bloombite-feeding-set",
        "shopify_product_id": "gid://shopify/Product/1007",
        "title": "BloomBite Silicone Feeding Set",
        "handle": "bloombite-silicone-feeding-set",
        "vendor": "Northstar Kids",
        "product_type": "Feeding Set",
        "status": "active",
        "jurisdiction_scope": "US, CA",
        "supplier_name": "Shenzhen SoftMeal Baby",
        "country_of_origin": "CN",
        "age_grade": "6m+",
        "tags": ["feeding", "silicone", "baby"],
        "variants": [
            {
                "id": "var-bb-clay",
                "shopify_variant_id": "gid://shopify/ProductVariant/2008",
                "sku": "BB-FS-CLAY",
                "title": "Clay",
                "barcode": "850100000008",
                "price": 34.0,
                "inventory_quantity": 72,
                "status": "active",
            }
        ],
        "documents": [
            {"id": "doc-bb-cpc", "title": "CPC - BloomBite Feeding Set", "doc_type": "CPC", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-142), "valid_until": iso_days_from_now(182), "verified_at": iso_days_from_now(-21), "source_url": "", "notes": "Children's product declaration current."},
            {"id": "doc-bb-lab", "title": "Feeding set lab report", "doc_type": "Lab Report", "issuer": "SGS", "status": "verified", "issued_at": iso_days_from_now(-130), "valid_until": iso_days_from_now(160), "verified_at": iso_days_from_now(-20), "source_url": "", "notes": "Lead, phthalates, and drop test coverage."},
            {"id": "doc-bb-track", "title": "Feeding set traceability label", "doc_type": "Tracking Label", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-80), "valid_until": iso_days_from_now(260), "verified_at": iso_days_from_now(-17), "source_url": "", "notes": "Lot code on package base."},
            {"id": "doc-bb-food", "title": "Food-contact declaration", "doc_type": "Food Contact", "issuer": "SoftMeal Baby", "status": "verified", "issued_at": iso_days_from_now(-75), "valid_until": iso_days_from_now(210), "verified_at": iso_days_from_now(-14), "source_url": "", "notes": "Silicone declaration and migration statement."},
        ],
        "missing_requirements": ["supplier_packet"],
    },
    {
        "id": "prod-cometpals-plush",
        "shopify_product_id": "gid://shopify/Product/1008",
        "title": "CometPals Night-Light Plush",
        "handle": "cometpals-night-light-plush",
        "vendor": "Northstar Kids",
        "product_type": "Electronic Plush",
        "status": "active",
        "jurisdiction_scope": "US, CA",
        "supplier_name": "Dongguan Moonbeam Electronics",
        "country_of_origin": "CN",
        "age_grade": "18m+",
        "tags": ["plush", "battery", "night light", "children"],
        "variants": [
            {
                "id": "var-cp-star",
                "shopify_variant_id": "gid://shopify/ProductVariant/2009",
                "sku": "CP-NP-STAR",
                "title": "Star",
                "barcode": "850100000009",
                "price": 44.0,
                "inventory_quantity": 54,
                "status": "active",
            }
        ],
        "documents": [
            {"id": "doc-cp-cpc", "title": "CPC - CometPals Plush", "doc_type": "CPC", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-132), "valid_until": iso_days_from_now(182), "verified_at": iso_days_from_now(-18), "source_url": "", "notes": "Children's electronics scope documented."},
            {"id": "doc-cp-lab", "title": "Electronics plush lab report", "doc_type": "Lab Report", "issuer": "Intertek", "status": "verified", "issued_at": iso_days_from_now(-120), "valid_until": iso_days_from_now(160), "verified_at": iso_days_from_now(-18), "source_url": "", "notes": "Mechanical and emissions screen."},
            {"id": "doc-cp-track", "title": "Plush traceability label", "doc_type": "Tracking Label", "issuer": "Northstar Kids", "status": "verified", "issued_at": iso_days_from_now(-90), "valid_until": iso_days_from_now(230), "verified_at": iso_days_from_now(-18), "source_url": "", "notes": "Batch code in battery compartment."},
            {"id": "doc-cp-battery", "title": "Battery thermal review", "doc_type": "Battery Review", "issuer": "Moonbeam Electronics", "status": "expired", "issued_at": iso_days_from_now(-480), "valid_until": iso_days_from_now(-15), "verified_at": iso_days_from_now(-450), "source_url": "", "notes": "Refresh required after supplier cell substitution."},
            {"id": "doc-cp-supplier", "title": "Electronics supplier packet", "doc_type": "Supplier Packet", "issuer": "Moonbeam Electronics", "status": "verified", "issued_at": iso_days_from_now(-90), "valid_until": iso_days_from_now(110), "verified_at": iso_days_from_now(-16), "source_url": "", "notes": "Current cell and PCB declarations."},
        ],
        "missing_requirements": ["warning_art"],
    },
]


ALERTS = [
    {
        "id": "alert-high-chair-latch",
        "source_name": "CPSC",
        "source_id": "cpsc-2026-101",
        "title": "High chairs recalled due to latch failures and fall hazard",
        "alert_date": iso_days_from_now(-14),
        "jurisdiction": "United States",
        "product_name": "Convertible high chairs",
        "hazard": "Latch can disengage, creating fall and entrapment hazards.",
        "description": "The recalled high chairs can unexpectedly fold when the rear latch does not fully engage. Consumers should stop use and quarantine affected inventory pending lot review.",
        "source_url": "https://www.cpsc.gov/Recalls",
        "severity": "critical",
        "status": "new",
    },
    {
        "id": "alert-carriers-buckle",
        "source_name": "CPSC",
        "source_id": "cpsc-2026-118",
        "title": "Infant carriers recalled after buckle webbing separation",
        "alert_date": iso_days_from_now(-28),
        "jurisdiction": "United States",
        "product_name": "Soft infant carriers",
        "hazard": "Webbing may detach from buckle housing, posing a fall hazard.",
        "description": "Consumers should stop using the recalled soft infant carriers immediately and contact the firm for inspection and replacement instructions.",
        "source_url": "https://www.cpsc.gov/Recalls",
        "severity": "high",
        "status": "triage",
    },
    {
        "id": "alert-shape-sorter-lead",
        "source_name": "Health Canada",
        "source_id": "hc-2026-072",
        "title": "Wooden shape sorter toy recalled for lead in surface coating",
        "alert_date": iso_days_from_now(-9),
        "jurisdiction": "Canada",
        "product_name": "Wooden sorting toys",
        "hazard": "Surface coating contains lead above allowable limits.",
        "description": "Health Canada published a recall notice for several imported wooden sorting toys after confirmatory paint testing. Sellers should isolate current stock and review coating supplier records.",
        "source_url": "https://recalls-rappels.canada.ca/",
        "severity": "high",
        "status": "new",
    },
    {
        "id": "alert-battery-plush-overheat",
        "source_name": "CPSC",
        "source_id": "cpsc-2026-141",
        "title": "Battery-powered plush toys recalled after overheating reports",
        "alert_date": iso_days_from_now(-5),
        "jurisdiction": "United States",
        "product_name": "Battery-powered plush toys",
        "hazard": "Battery compartment can overheat and melt, posing burn hazard.",
        "description": "The firm received reports of plush toys overheating during charging. Sellers should halt fulfillment, identify impacted batches, and document customer outreach decisions.",
        "source_url": "https://www.cpsc.gov/Recalls",
        "severity": "critical",
        "status": "new",
    },
    {
        "id": "alert-bath-seat-suction",
        "source_name": "Health Canada",
        "source_id": "hc-2026-077",
        "title": "Baby bath seats recalled due to unexpected tip-over",
        "alert_date": iso_days_from_now(-18),
        "jurisdiction": "Canada",
        "product_name": "Infant bath seats",
        "hazard": "Suction cups may release unexpectedly, creating a drowning hazard.",
        "description": "Bath seats sold under multiple private labels may tip when suction cups lose seal strength. Review lot traceability and operator instructions before resuming sales in Canada.",
        "source_url": "https://recalls-rappels.canada.ca/",
        "severity": "critical",
        "status": "triage",
    },
]


CASE_OVERRIDES = {
    ("alert-high-chair-latch", "prod-meadownest-high-chair"): {
        "owner": "Avery Chen",
        "triage_status": "action_needed",
        "decision": "Quarantine Sage and Oat lots 24-08 through 24-11",
        "priority": "high",
        "summary": "Inventory hold opened while supplier confirms latch revision dates.",
        "events": [
            {"event_type": "note", "actor_name": "Avery Chen", "note": "Flagged exact overlap between high-chair latch recall pattern and MeadowNest latch architecture.", "source_url": "https://www.cpsc.gov/Recalls"},
            {"event_type": "decision", "actor_name": "Avery Chen", "note": "Warehouse asked to quarantine all on-hand lots until hinge-latch verification completes.", "source_url": ""},
        ],
    },
    ("alert-carriers-buckle", "prod-littleharbor-carrier"): {
        "owner": "Mira Lewis",
        "triage_status": "under_review",
        "decision": "Waiting on buckle resin and tensile re-test packet",
        "priority": "medium",
        "summary": "Supplier packet requested; holding outbound wholesale PO only.",
        "events": [
            {"event_type": "note", "actor_name": "Mira Lewis", "note": "Carrier buckle architecture looks similar but SKU hardware vendor differs. Reviewing latest SGS report and BOM revision.", "source_url": "https://www.cpsc.gov/Recalls"},
        ],
    },
    ("alert-shape-sorter-lead", "prod-brightloop-sorter"): {
        "owner": "Avery Chen",
        "triage_status": "monitoring",
        "decision": "Monitor only after confirming coating supplier lot traceability",
        "priority": "medium",
        "summary": "No direct supplier overlap yet; coating cert check remains open.",
        "events": [
            {"event_type": "note", "actor_name": "Avery Chen", "note": "Alert is in-category and jurisdictionally relevant for Canada, but current paint supplier differs from recalled firms.", "source_url": "https://recalls-rappels.canada.ca/"},
        ],
    },
    ("alert-battery-plush-overheat", "prod-cometpals-plush"): {
        "owner": "Mira Lewis",
        "triage_status": "action_needed",
        "decision": "Pause DTC fulfillment until fresh battery thermal review lands",
        "priority": "high",
        "summary": "Overheat alert plus expired battery review makes this demo's sharpest active case.",
        "events": [
            {"event_type": "note", "actor_name": "Mira Lewis", "note": "Battery review expired last month and the alert pattern overlaps charging behavior on CometPals.", "source_url": "https://www.cpsc.gov/Recalls"},
        ],
    },
    ("alert-bath-seat-suction", "prod-pebblepath-bath-seat"): {
        "owner": "Avery Chen",
        "triage_status": "under_review",
        "decision": "Review suction cup lot traceability and Canadian instructions",
        "priority": "high",
        "summary": "Bath-seat alert overlaps exactly on product type and hazard profile.",
        "events": [
            {"event_type": "note", "actor_name": "Avery Chen", "note": "Canadian bath-seat notice is directly relevant; reviewing suction-cup supplier change from October.", "source_url": "https://recalls-rappels.canada.ca/"},
        ],
    },
}


def build_seed_products() -> list[dict]:
    seeded: list[dict] = []
    for product in PRODUCTS:
        classification = classify_product(product["title"], product["product_type"], product["tags"])
        seeded.append(
            {
                **product,
                "classification": classification,
                "evidence_template": build_evidence_template(classification),
            }
        )
    return seeded
